[package]
name = "team1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
veil = "0.1.7"
log = "0.4.14"
env_logger = "0.9.0"
rand = "0.8.5"
rand_distr = "0.4.3"
statrs = "0.16.0"
csv = "1.3.0"
